name: Test
on:
  - push
jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run sequence.py
        run: |
          cat greek.txt | python ../sequence.py > output.csv
        working-directory: test

      - name: Check sequence.py output
        run: |
          cmp --silent output.csv greek.csv || (echo "Files output.csv and greek.csv differ" && exit 1)
        working-directory: test

      - name: Run poetry.py
        run: |
          cat rilke.txt | python ../poetry.py > output.csv
        working-directory: test

      - name: Check poetry.py output
        run: |
          cmp --silent output.csv rilke.csv || (echo "Files output.csv and rilke.csv differ" && exit 1)
        working-directory: test