name: Build and test
on:
  - push
jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run script
        run: |
          cat greek.txt | python ../sequence.py > output.csv
        working-directory: test

      - name: Compare output
        run: |
          cmp --silent output.csv greek.txt || (echo "Files output.csv and greek.csv differ" && exit 1)
        working-directory: test
